### ISSUE TITLE
undefined name kwargs

### ISSUE THREAD

**Issue by innateessence** [bcbnz/python-rofi#1]
Line 378 :
args.extend(self._common_args(**kwargs))

I addressed this here :
https://github.com/JackofSpades707/python-rofi/commit/544532bcb91fb5fe37236f4f76df008a30a6f3cd#diff-2037d63fbbc4280a03fa2e7c5383d45bR339

Thanks for building such a wonderful module :)

**Comment by Foxboron** [comment]
I created a PR for this.

**Comment by bcbnz** [comment]
Thanks for the report! Don't know how I didn't run into that myself. I've merged the pull request.
