### ISSUE TITLE
Add python-rofi to pypi

### ISSUE THREAD

**Issue by Foxboron** [bcbnz/python-rofi#3]
Love the project. Would be great if it could be added into pypi. It would just need a setup.py, which i can write if @bcbnz wants.

**Comment by bcbnz** [comment]
I'll get onto that. I've been meaning to come back to this (want to use it in a couple of projects) and sort a few things out :).

**Comment by bcbnz** [comment]
Done! It's up at https://pypi.python.org/pypi/python-rofi/. Thanks for raising this.

**Comment by Foxboron** [comment]
Packaged for AUR :shipit:  https://github.com/Foxboron/PKGBUILDS/blob/master/python-rofi/PKGBUILD

**Comment by bcbnz** [comment]
Awesome! I would suggest adding rofi to the dependencies though... :-).
